### ISSUE TITLE
Will this library be maintained for a long time?

### ISSUE THREAD

**Issue by RWDai** [NullpointerW/go-qbittorrent-apiv4#1]

**Comment by RWDai** [comment]
Is this repository still maintenance?

**Comment by NullpointerW** [comment]
> Is this repository still maintenance?

I've only maintained what's necessary for my own project. It's currently sufficient, and I might keep it this way for a while. If you come across APIs that you need but aren't included, you can fork the project and add them yourself or submit a pull request (PR).
